# footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint: [[-0.21, -0.165], [-0.21, 0.165], [0.21, 0.165], [0.21, -0.165]]

# robot_radius: 0.1
footprint_padding: 0.03 ### use it when we have map

robot_base_frame: base_link
update_frequency: 8.0
publish_frequency: 6.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5 ### for barn is 5 for having map 2.5
raytrace_range: 6 ##for barn is 6 for having map 3.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

##delete it always except having map
# plugins:
# - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
# - {name: inflater_layer, type: "costmap_2d::InflationLayer"}


obstacles_laser:
    observation_sources: laser
    ###chnage it to /scan using robotont for jackal /front/scan
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: front/scan, inf_is_valid: true}

inflation:
    inflation_radius: 0.05 #for barn is 0.05#for jackal and dynamic 0.15

planner_patience: 1
controller_patience: 1
recovery_behavior_enabled: false
